apiVersion: appconnect.ibm.com/v1beta1
kind: IntegrationRuntime
metadata:
  labels:
    backup.appconnect.ibm.com/component: integrationruntime
  name: customer-delete-gdpr
  namespace: cp4i
spec:
  license:
    accept: true
    license: L-KZVS-2G3FW4
    use: CloudPakForIntegrationProduction
  replicas: 1
  template:
    spec:
      containers:
        - name: runtime
          resources:
            limits:
              cpu: 500m
              memory: 512Mi
            requests:
              cpu: 500m
              memory: 512Mi
  version: '12.0'
  barURL:
  configurations:
    - voda-poc
    - statistics-server-conf
    - git-barauth
  flowType:
    designerAPIFlow: true
